List<String> questions = [
  "How to make a good and effective resume based on your profile?",
  "Where can I find a student accommodation near NIT Raipur?",
  "What are the rounds that take place in Analyst profile Companies?",
  "What are some good On-Campus Placement Hacks?",
  "What are some good project topics for 3rd year computer science engineering students?",
  "I have done a course on Programming language, what should I do next or where should I apply it?",
  "What is the best way to learn a programming language effectively and efficiently?",
  "How can a student from NIT develop his skills to match those of the students of IIT?",
  "How and from where to make a resume?",
  "What are ways to get an internship at a startup?",
];
List<String> answers = [
  "Keep your profile concise. A resume profile should be between one and four (brief) sentences long. You can write your profile as a short paragraph or in bullet form.",
  "Getting a seat in NIT Raipur hostel (both girls and boys) is a case of getting a rank in merit list for hostel, plus a chance if category wise consideration is there or not. One can find accomodation in DDU and kota at best price.",
  "First: Aptitute, then in some compaines there may be or technical round and Final round is HR round if you clear GD and technical rounds",
  "Apply with a crisp and clear resume,  Prepare for interview questions,  Practice with mock interviews",
  "Voice-based E-mail for the Blind, Unique ID (UID) Management System Project, Online Voting Using Bluetooth Enabled Mobile Phone, CALTOOL Computer-Aided Learning Tool, Data-Efficient Robot Reinforcement Learning",
  "Getting busy with your further self-education, it's very important not to concentrate on one, too narrow field. In 2017 «a web-programmer in Ruby who can do anything» is very much like «a worker with a shovel who can do anything» – a laborer, in itself. And even if you are a Ruby-expert – often it looks like «a worker with a VERY good shovel».",
  "Make Your Fundamentals Clear, Learn By Doing, Practicing and Not Just Reading, Code By Hand and Share, Teach, Discuss and Ask For Help",
  "First of all, get the complex of any IIT or NIT out of your mind. Take a note, even if you are not from any premier engineering college, you can still make a fortune in India and abroad. You may not be having the brand value of the IIT/NIT but improve your skills and focus on holistic development.",
  "Bete khud hi banao apna resume",
  "I wish to share a few links that might help you find a suitable position for a internship of your area of interest be it a startup or an established firm. Please find the detailed links description for the Internships: LinkedIn Jobs, Glassdoor, Indeed and Angle.co",
];
List<String> dateAsked = [
  "21 March 2021",
  "2 March 2021",
  "1 March 2021",
  "10 March 2021",
  "25 March 2021",
  "26 March 2021",
  "13 March 2021",
  "27 March 2021",
  "5 March 2021",
  "8 March 2021",
];
List<int> noOfAnswers = [
  2,
  9,
  2,
  8,
  1,
  5,
  2,
  1,
  10,
  1,
];
List<int> noOfUpVotes = [
  12,
  9,
  1,
  18,
  13,
  5,
  21,
  10,
  15,
  1,
];
